### PR TITLE
feat: fallback to packages defined in `package.json`

### PR DESCRIPTION
**Pull request by sparten11740**
Use `getPackagePaths` from `@exodus/lerna-utils` to get the lerna managed packages. The function supports packages that are defined in `package.json` for yarn workspaces and which are missing the `packages` property in `lerna.json`.

### CODE REVIEW

**Review by r4vn — APPROVED** [review]
utACK

**Comment by mvayngrib** [comment]
checks failing

**Comment by sparten11740** [comment]
> checks failing

`@exodus/lerna-utils` needs to be public on npm, requested in slack

**Review by mvayngrib — APPROVED** [review]
utACK

**Pull request merged**
